[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "dggs-benchmarking"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.34" }

[tasks]

[dependencies]
jupyterlab = ">=4.4.5,<5"
jupyter-resource-usage = ">=1.1.1,<2"
jupyterlab_code_formatter = ">=3.0.2,<4"
black = "*"
isort = "*"
ruff = "*"
python = "3.12.*"
jedi-language-server = "*"
ipykernel = ">=6.30.1,<7"
xarray = ">=2025.9.0,<2026"
zarr = ">=2,<3"
pyproj = ">=3.7.2,<4"
pystac-client = ">=0.9.0,<0.10"
xarray-eopf = ">=0.2.0,<0.3"
matplotlib-base = ">=3.10.3,<4"

[environments]
ellipsoidal-healpix = ["ellipsoidal-healpix"]

[pypi-dependencies]
healpix-geo = "*"

[feature.ellipsoidal-healpix.dependencies]
pandas = "*"
matplotlib = "*"
seaborn = "*"
evcxr = "*"
fastparquet = ">=2024.11.0,<2025"
